### ISSUE TITLE
"VulcanSerial/SerialPort.hpp" No such file or directory

### ISSUE THREAD

**Issue by eleven110** [ZJU-FAST-Lab/3D2M-planner#7]
![微信截图_202401261903522](https://github.com/ZJU-FAST-Lab/3D2M-planner/assets/85616395/a3e34791-254f-4c97-a1dc-10d0d70f8818)
how can i solve this issue?

**Comment by Kayledu** [comment]
I have resolved this issue and need to place the VulcanSerial file directory in the/etc/local/include directory and the libVulcanSerial.a file in the/etc/local/lib directory.
